### PR TITLE
Rename 'namespace' foreign keys to 'app_config'

### PR DESCRIPTION
**Pull request by mikek**
As described in #67

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1:

**Comment by mikek** [comment]
@tom @yakky I hope we have not much users now. Should we maintain a changelog from version 0.1.0 onwards?

**Comment by intellectronica** [comment]
@mikek changelog is a great idea!

**Comment by mikek** [comment]
We can move most of the README (and, probably, changelog) to docs directory later.

**Pull request merged**
