### PR TITLE
don't float published fields

### PR DESCRIPTION
**Pull request by lory87**
**This pull request fixes the following issues**:

|BEFORE|AFTER|
|---|---|
|capture-for-jira-screenshot-20160319-125917-240|screen shot 2016-04-08 at 12 43 14|

### CODE REVIEW

**Comment by FinalAngel** [comment]
does that also fix #1 @lory87 ?

**Comment by lory87** [comment]
@FinalAngel #1 is fixed already with another ticket in admin styles

**Comment by FinalAngel** [comment]
then LGTM :)

**Comment by mikek** [comment]
LGTM

**Pull request merged**
