### PR TITLE
Add template_prefix to AppConfig

### PR DESCRIPTION
**Pull request by piotrjakimiak**
Hi,

I had issue which required adding multiple instances of aldryn_newsblog, but with different templates.

I've added new setting for NewsBlogConfig, which allow to add prefix to template path.

~~I have some problems with adding migrations to Django 1.7.~~

### CODE REVIEW

**Comment by piotrjakimiak** [comment]
Should I describe it in readme?

**Comment by mkoistinen** [comment]
Looks like a pretty comprehensive PR, thank you.

However, in the most recent release, we've replaced {% extends base.html %} with {% extends CMS_TEMPLATE %}, this should allow you to choose your template on a per-apphook basis with the tools already supplied in the CMS, correct?

**Comment by piotrjakimiak** [comment]
@mkoistinen in my project I have to create two seperate pages one for news and second for blog. Blog and news have different HTML codes (i've bought bootstrap theme) for objects lists and plugins.

I can use 'if' templatetag to check which instance is rendered, but i think its not proper way.

**Comment by mkoistinen** [comment]
@piotrjakimiak Seems reasonable. Let me invite some review from some key people.

@FinalAngel can you have a look at this and let me know if this is inline with boilerplates, etc?

**Comment by FinalAngel** [comment]
@mkoistinen I'm not really sure /cc @stefanfoulis

**Comment by piotrjakimiak** [comment]
Any chance for it to be merged? I really need this and i don't want to create seperate branch for myself because of migrations.

**Comment by mkoistinen** [comment]
@piotrjakimiak two points to consider:

1. Can you make this fallback to non-prefixed templates so you don't have to copy everything for a given prefix if you don't need them?
2. Can the resulting template path be more like this: /aldryn_newsblog/[prefix]/... rather than the other way around?

Thanks again!

**Comment by piotrjakimiak** [comment]
@mkoistinen 

Ad. 1. Prefix is added only if template_prefix is defined otherwise it fallback to non-prefixed version.
Ad. 2. Done. See https://github.com/aldryn/aldryn-newsblog/pull/172/files#diff-9e1c3dc1b188b57279da3c5eec46a5a3R7 for details

**Comment by mkoistinen** [comment]
Thank you for your contributions!

**Comment by piotrjakimiak** [comment]
Thanks for pushing it.

**Comment by shadow-identity** [comment]
I've got 500 error after upgrading to 0.9, may it be problem with this merge?
```
Environment:


Request Method: GET
Request URL: http://localhost/en/blog/

Django Version: 1.7.7
Python Version: 2.7.9
Installed Applications:
('djangocms_admin_style',
 'djangocms_text_ckeditor',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.admin',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'cms',
 'menus',
 'sekizai',
 'treebeard',
 'djangocms_style',
 'djangocms_column',
 'djangocms_file',
 'djangocms_flash',
 'djangocms_googlemap',
 'djangocms_inherit',
 'djangocms_link',
 'djangocms_picture',
 'djangocms_teaser',
 'djangocms_video',
 'reversion',
 'mysite',
 'aldryn_apphooks_config',
 'aldryn_boilerplates',
 'aldryn_categories',
 'aldryn_newsblog',
 'aldryn_people',
 'aldryn_reversion',
 'easy_thumbnails',
 'filer',
 'parler',
 'taggit',
 'sortedm2m')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.doc.XViewMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware',
 'cms.middleware.language.LanguageCookieMiddleware')


Traceback:
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/cms/utils/decorators.py" in inner
  16.         return func(request, *args, **kwargs)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/aldryn_newsblog/views.py" in dispatch
  57.         return super(EditModeMixin, self).dispatch(request, *args, **kwargs)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/aldryn_apphooks_config/mixins.py" in dispatch
  15.         self.namespace, self.config = get_app_instance(request)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/aldryn_apphooks_config/utils.py" in get_app_instance
  27.                 config = app.get_config(namespace)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/aldryn_apphooks_config/app_base.py" in get_config
  14.             return self.app_config.objects.get(namespace=namespace)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/models/query.py" in get
  351.         num = len(clone)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/models/query.py" in __len__
  122.         self._fetch_all()
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/models/query.py" in _fetch_all
  966.             self._result_cache = list(self.iterator())
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/parler/managers.py" in iterator
  112.         for obj in base_iterator:
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/models/query.py" in iterator
  265.         for row in compiler.results_iter():
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in results_iter
  700.         for rows in self.execute_sql(MULTI):
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
  786.             cursor.execute(sql, params)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  81.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  65.                 return self.cursor.execute(sql, params)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/utils.py" in __exit__
  94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  65.                 return self.cursor.execute(sql, params)
File "/home/nedr/ssd/progs/env/nedrigailov_tk/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py" in execute
  485.         return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /en/blog/
Exception Value: no such column: aldryn_newsblog_newsblogconfig.template_prefix
```

**Comment by piotrjakimiak** [comment]
Have You done `./manage.py migrate`?

**Comment by shadow-identity** [comment]
yep it works after migrate. thank you

**Comment by mkoistinen** [comment]
To anyone else landing here. The migration requires django-parler>=1.4.0, the next release of NewsBlog will make this requirement explicit.

**Pull request merged**
