### PR TITLE
Extend CMS_TEMPLATE in base template

### PR DESCRIPTION
**Pull request by mkoistinen**

### CODE REVIEW

**Comment by vinitkumar** [comment]
@mkoistinen I still get wrong template when I publish the page.

**Comment by mkoistinen** [comment]
You can now change the template used by using the page settings:

image

**Comment by vinitkumar** [comment]
I already did. It still doesn't solve my problem. I think the bug still remains. I am on `aldryn-newsblog==0.8.4` which has your fix. But it does't really help. Here is the screengrab that will let you know how it goes wrong. Also, I still get these warnings in my console. 
newsblog-bug

``
Application url changed and urls_need_reloading signal fired. Please reload the urls.py or restart the server```

I have restarted the app after adding the application, still it doesn't really help.

**Comment by mkoistinen** [comment]
@vinitkumar I just checked, the feature works as expected. You should review your templates to make sure it is meaningful to extend the CMS_TEMPLATE you choose.

**Pull request merged**
