### PR TITLE
Added return false on any plugin error

### PR DESCRIPTION
**Pull request by Marketionist**
**This PR adds ```return false``` on any plugin error**

### CODE REVIEW

**Comment by intellectronica** [comment]
:+1:

**Comment by Marketionist** [comment]
The problem tends to be in ```adds a new article on the page``` test in ```newsBlogPage.applicationSelect.sendKeys('NewsBlog');``` - need some more time to investigate on alternative fix

**Comment by vxsx** [comment]
FE :+1:

**Comment by mkoistinen** [comment]
:+1:

**Pull request merged**
