### PR TITLE
Updated README.rst

### PR DESCRIPTION
**Pull request by FinalAngel**
To make it more clear that it can be used for django CMS

### CODE REVIEW

**Comment by evildmp** [comment]
Commit subject: "Updated" (past tense please)

**Comment by vxsx** [comment]
@FinalAngel hey, would you mind also removing the browser matrix as it's no longer valid? also in other essential addons

**Comment by FinalAngel** [comment]
@vxsx ofc

**Comment by vxsx** [comment]
also line 63

**Comment by vxsx** [comment]
👍

**Pull request merged**
