### PR TITLE
Exclude tests from coverage

### PR DESCRIPTION
**Pull request by yakky**
Tests should be excluded from coverage

### CODE REVIEW

**Comment by mikek** [comment]
I find it helpful to see what test code was not executed. http://stackoverflow.com/a/1629194 (This is not a very hot topic, but rather generic one.) No real objections to the PR, though.

**Comment by yakky** [comment]
That's a valid point, actually, but it skewes the coverage stas(wchi is just a number with dubious value, but nevertheless) I'm ok with whatver decision

**Comment by mikek** [comment]
If coverage numbers is one of the main concerns, we can still exclude that code: http://nedbatchelder.com/code/coverage/excluding.html#excluding
Let's see if someone else has some strong ideological or religious concerns.

**Comment by chronossc** [comment]
I'm with @mikek on that. Is good to know what test was not executed, after all, there is something wrong with that code in test if it is not executed.

**Pull request closed without merging**
