### PR TITLE
Configurable publish option

### PR DESCRIPTION
**Pull request by yakky**
This implements aldryn/aldryn-apphooks-config#13 interface to allow setting the default value for publish option

### CODE REVIEW

**Comment by yakky** [comment]
Ping @mkoistinen @intellectronica

**Comment by intellectronica** [comment]
:+1: Cool!

**Comment by yakky** [comment]
It will be cooler when the tests will pass 😁 finalising soon, anyway

**Comment by yakky** [comment]
@mkoistinen added dependency on aldryn-apphook-config 0.2.0

**Pull request merged**
